name: Daily Commit

on:
  schedule:
    - cron: '30 5 * * *'
  workflow_dispatch:

jobs:
  commit-job:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # ✅ gives permission to push code

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Make a commit by 23f2002045@ds.study.iitm.ac.in
        run: |
          echo "Updated on $(date)" > daily-log.txt
          git config user.name "Auto Commit Bot"
          git config user.email "23f2002045@ds.study.iitm.ac.in"
          git add daily-log.txt
          git commit -m "Daily update: $(date)" || echo "No changes to commit"
          git push
        env:
          # ✅ GitHub automatically sets this token so the action can push
          GIT_ASKPASS: /bin/true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

