name: Daily Commit

on:
  schedule:
    - cron: '30 5 * * *'  # Runs every day at 5:30 AM UTC
  workflow_dispatch:       # Optional manual run button

jobs:
  commit-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Make a commit by 23f2002045@ds.study.iitm.ac.in
        run: |
          echo "Updated on $(date)" >> daily-log.txt
          git config user.name "Auto Commit Bot"
          git config user.email "23f2002045@ds.study.iitm.ac.in"
          git add daily-log.txt
          git commit -m "Daily update: $(date)"
          git push
